feat(build): support for multi arch container image
openebs/zfs-localpv pull request #233
Opened 2020-11-03 15:56 UTC by prateekpandey14

Signed-off-by: prateekpandey14 <prateek.pandey@mayadata.io>

**Why is this PR required? What issue does it fix?**:
PR add multi arch support for zfs-localpv container images

**Does this PR require any upgrade changes?**:

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Any additional information for your reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [ ] Fixes #<issue number>
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Has the change log section been updated?
- [ ] Commit has unit tests
- [ ] Commit has integration tests
- [ ] (Optional) Are upgrade changes included in this PR? If not, mention the issue/PR to track:
- [ ] (Optional) If documentation changes are required, which issue on https://github.com/openebs/openebs-docs is used to track them:

2020-11-05 10:28 UTC, akhilerm commented on .github/workflows/build.yml
> +          echo "TAG: ${CI_TAG}"
```suggestion
          echo "TAG: ${CI_TAG}"
          
```

2020-11-05 10:29 UTC, akhilerm commented on .github/workflows/release.yml
> +          echo "RELEASE_TAG ${TAG}"
```suggestion
          echo "RELEASE_TAG ${TAG}"
          
```

2020-11-05 10:30 UTC, akhilerm commented on Makefile.buildx.mk
> +	export PLATFORMS="linux/amd64,linux/arm64,linux/ppc64le"
why is armv7 not included?

2020-11-05 10:35 UTC, akhilerm reviewed
a few nitpick comments and a question on the `linux/arm/v7` platform.

2020-11-05 10:55 UTC, prateekpandey14 commented on Makefile.buildx.mk
> +	export PLATFORMS="linux/amd64,linux/arm64,linux/ppc64le"
added

2020-11-05 11:00 UTC, shubham14bajpai approved these changes
lgtm

2020-11-06 06:22 UTC, akhilerm approved these changes
/lgtm

2020-11-09 12:26 UTC, akhilerm commented on .github/workflows/build.yml
> +          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
```suggestion
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
```

2020-11-09 12:26 UTC, akhilerm commented on .github/workflows/release.yml
> +          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
```suggestion
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
```

2020-11-09 12:27 UTC, akhilerm requested changes
@prateekpandey14 A change is required for the dockerhub credential env to make it consistent across all repositories.

2020-11-09 13:03 UTC, prateekpandey14 commented on .github/workflows/release.yml
> +          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
done

2020-11-09 14:59 UTC, akhilerm approved these changes
LGTM

2020-11-11 05:38 UTC, kmova commented
@prateekpandey14 - can you get travis to push the zfs-driver-amd64 image?

2020-11-11 06:25 UTC, prateekpandey14 commented
>@prateekpandey14 - can you get travis to push the zfs-driver-amd64 image?

Done

2020-11-11 08:45 UTC, kmova approved these changes

2020-11-11 08:46 UTC, merged

2020-11-11 15:24 UTC, pawanpraka1 commented
@prateekpandey14 can you raise a PR for the changelog?