feat(helm): add github action for chart test and release
openebs/zfs-localpv pull request #250
Opened 2020-12-07 11:36 UTC by shubham14bajpai

Signed-off-by: shubham <shubham.bajpai@mayadata.io>

**What this PR does?**:

This PR adds github action CI for zfs-localpv helm chart lint, test and release.

**Note:** The zfs-localpv helm charts will reside in a directory structure: `deploy/helm`

The following are the details of changes : 
1. Adds `Chart Lint and Test` action to test and lint the chart changes. 
- This action is only triggered if there is any change in the content of `deploy/helm` directory.

2. Modifies the existing `Go` action.
- As a result of the modification, the action will not run for pull requests if there are changes in the `deploy/helm` directory.

3. Adds a `Release Charts` action to release the helm chart. 
- This action triggers only when the push in against `develop` and there is a change in the content of `deploy/helm` directory.

**Checklist:**
- [ ] Fixes #<issue number>
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Has the change log section been updated?
- [ ] Commit has unit tests
- [ ] Commit has integration tests
- [ ] (Optional) Are upgrade changes included in this PR? If not, mention the issue/PR to track:
- [ ] (Optional) If documentation changes are required, which issue on https://github.com/openebs/openebs-docs is used to track them:

2020-12-07 16:05 UTC, akhilerm commented on .github/workflows/chart-lint-test.yml
> +      - develop
zfs-localpv uses `master` branch
```suggestion
      - master
```

2020-12-07 16:05 UTC, akhilerm commented on .github/workflows/chart-lint-test.yml
> +      - develop
```suggestion
      - master
```

2020-12-07 16:06 UTC, akhilerm commented on .github/workflows/release-charts.yml
> +      - develop
```suggestion
      - master
```

2020-12-07 16:07 UTC, akhilerm requested changes
@shubham14bajpai The branch name needs to be changed from develop to master.

2020-12-09 11:10 UTC, akhilerm approved these changes
LGTM

2020-12-09 11:44 UTC, prateekpandey14 approved these changes
lgtm

2020-12-11 13:30 UTC, merged