feat(scheduling): add zfs pool capacity tracking
openebs/zfs-localpv pull request #335
Opened 2021-05-20 06:27 UTC by shubham14bajpai

Signed-off-by: shubham <shubham.bajpai@mayadata.io>

**Why is this PR required? What issue does it fix?**:

**What this PR does?**:

**Does this PR require any upgrade changes?**:

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Any additional information for your reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [ ] Fixes #<issue number>
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Has the change log section been updated?
- [ ] Commit has unit tests
- [ ] Commit has integration tests
- [ ] (Optional) Are upgrade changes included in this PR? If not, mention the issue/PR to track:
- [ ] (Optional) If documentation changes are required, which issue on https://github.com/openebs/openebs-docs is used to track them:

2021-05-21 12:27 UTC, akhilerm commented on deploy/yamls/zfsnode-crd.yaml
> +  - name: v1
Is the version `v1` or `v1alpha1`?

2021-05-21 12:29 UTC, akhilerm commented on pkg/apis/openebs.io/zfs/v1/register.go
> +		&ZFSNode{},
@pawanpraka1 Doesn't this CR need to be in `v1alpha1` or all ZFS CRs are `v1`

2021-05-21 12:30 UTC, akhilerm commented on pkg/apis/openebs.io/zfs/v1/zfsnode.go
> +// Pool specifies attributes of a given zfs pool exists on node.
```suggestion
// Pool specifies attributes of a given zfs pool that exists on the node.
```

2021-05-21 12:32 UTC, akhilerm commented on pkg/driver/agent.go
> +			klog.Fatalf("Failed to start LVM node controller: %s", err.Error())
```suggestion
			klog.Fatalf("Failed to start ZFS node controller: %s", err.Error())
```

2021-05-21 12:34 UTC, akhilerm commented on pkg/driver/controller.go
> +	vgParam := helpers.GetInsensitiveParameter(&params, "volgroup")
`s/volgroup/poolname/`.

volgroup needs to be changed to pool name

2021-05-21 12:35 UTC, akhilerm commented on pkg/driver/controller.go
> +		// lv size that gets fit in given vg.
Change comment as per ZFS terms.

2021-05-21 12:35 UTC, akhilerm commented on pkg/driver/controller.go
> +		for _, vg := range zfsNode.Pools {
```suggestion
		for _, zpool := range zfsNode.Pools {
```

2021-05-21 12:38 UTC, akhilerm commented on pkg/mgmt/zfsnode/zfsnode.go
> +func (c *NodeController) listZFSVolumeGroup() ([]apis.Pool, error) {
```suggestion
func (c *NodeController) listZFSPool() ([]apis.Pool, error) {
```

2021-05-21 12:38 UTC, akhilerm commented on pkg/mgmt/zfsnode/zfsnode.go
> +	pools, err := c.listZFSVolumeGroup()
```suggestion
	pools, err := c.listZFSPool()
```

2021-05-21 12:55 UTC, akhilerm requested changes
given some comments.

2021-05-31 07:41 UTC, akhilerm approved these changes
LGTM

2021-05-31 07:42 UTC, akhilerm commented on deploy/yamls/zfsnode-crd.yaml
> +  - name: v1
We will be using the v1 version for zfsnode CRs

2021-05-31 12:14 UTC, pawanpraka1 commented on pkg/mgmt/zfsnode/zfsnode.go
> +		klog.Infof("Successfully synced '%s'", key)
let us remove this (or put it uder more verbose) as it will pollute the log every minute.

2021-05-31 12:23 UTC, pawanpraka1 approved these changes
looks good.

2021-05-31 13:29 UTC, merged