chore(docs): Update README.md
openebs/zfs-localpv pull request #473
Opened 2023-09-09 18:25 UTC by ukd1

**Why is this PR required? What issue does it fix?**:
It makes the README more readable

**What this PR does?**:
It updates the readme to be:
1. a little more consistent - spacing, use of semi-colons, bash example formatting (i.e. $ vs no $ for examples), use of sudo
2. uses bash / yaml formatting for code blocks instead of none, which helps the reader with a little extra syntax highlighting
3. uses [notes / warning](https://github.com/orgs/community/discussions/16925) blocks to help highlight things of note. However, for anyone reviewing this - the notes and warnings somehow don't look super nice / correct in preview, but do work outside of comments in docs. Here is an example: https://gist.github.com/ukd1/84ffd58ba7c2275713aca7d8081b9d5e
4. some minor grammar changes

**Does this PR require any upgrade changes?**:
No, it's just doc / text changes

**If the changes in this PR are manually verified, list down the scenarios covered:**:
I read re-read the changes, and think they make it better.

2023-09-13 04:02 UTC, sinhaashish commented
@ukd1  : can you please sign your commit.

2023-09-13 04:13 UTC, sinhaashish approved these changes
looks good

2023-09-13 04:17 UTC, hrudaya21 commented
LGTM, Commit Sign is needed.

2023-09-13 05:58 UTC, niladrih requested changes
Looks good, requires a DCO sign-off

2023-09-13 05:58 UTC, niladrih commented on README.md
> +Before installing the ZFS-LocalPV driver please make sure your Kubernetes Cluster meets the following prerequisites :
nit: whitespace character before the ':'
```suggestion
Before installing the ZFS-LocalPV driver please make sure your Kubernetes Cluster meets the following prerequisites:
```

2023-09-13 05:58 UTC, niladrih commented on README.md
> +We can install the latest release of OpenEBS ZFS driver by running the following command :
nit: whitespace character before ':'
```suggestion
We can install the latest release of OpenEBS ZFS driver by running the following command:
```

2023-09-17 19:44 UTC, ukd1 commented
> Looks good, requires a DCO sign-off

Is that easy to do?

2023-09-17 19:48 UTC, ukd1 commented
@niladrih ✅

2023-09-17 19:50 UTC, niladrih approved these changes
Awesome, LGTM.

2023-09-17 19:50 UTC, merged

2023-09-17 19:51 UTC, ukd1 commented
BTW @niladrih the changes you made actually make the doc inconsistent - before there were things like `something something :` and `something something:` -- I changed (most? all?) to be ` :` - the changes I just accepted (without recalling why I did them) now make it mixed.

I don't really mind if it's ` :` or `:` before an example, but the mix makes my OCD go nuts. Which do you prefer, and I'll update them all

2023-09-17 19:55 UTC, niladrih commented
Sure @ukd1. The issue seems to be missing line breaks. With markdown files, ending lines with two spaces at the end breaks the line. When you update the lines, adding line breaks should work.

Found this here: https://github.com/mattcone/markdown-guide/blob/master/_basic-syntax/line-breaks.md