test(snapshot): add snapshot and clone test for raw block
openebs/zfs-localpv pull request #559
Opened 2024-07-15 09:08 UTC by sinhaashish

2024-07-15 11:56 UTC, Abhinandan-Purkait requested changes

2024-07-15 11:56 UTC, Abhinandan-Purkait commented on tests/provision_test.go
>  	deleteAppDeployment(appName)
Please add the cleanup steps as well for the created resources as above in the filesystem one.

2024-07-16 06:03 UTC, Abhinandan-Purkait approved these changes

2024-07-16 06:54 UTC, w3aman approved these changes

2024-07-16 06:59 UTC, merged