test(compression): verify various compression algo test
openebs/zfs-localpv pull request #562
Opened 2024-07-16 06:05 UTC by sinhaashish

2024-07-16 06:22 UTC, Abhinandan-Purkait requested changes
We should be testing the creating and property update both.

2024-07-19 05:04 UTC, Abhinandan-Purkait approved these changes

2024-07-19 05:04 UTC, Abhinandan-Purkait commented on tests/provision_test.go
> +	///
Not needed?

2024-07-19 05:04 UTC, Abhinandan-Purkait commented on tests/provision_test.go
> +		// verify the ddedup functionality
ddedup --> dedup

2024-07-19 05:04 UTC, Abhinandan-Purkait commented on tests/utils.go
> +		print(vol)
Not needed?

2024-07-19 05:04 UTC, Abhinandan-Purkait commented on tests/utils.go
> +	println(" Inside VerifyZFSVolumePropEdit ashish {%s}", pvcObj.Spec.VolumeName)
Not needed?

2024-07-24 06:14 UTC, sinhaashish commented
closing this as PR https://github.com/openebs/zfs-localpv/pull/570 is raised for this

2024-07-24 06:14 UTC, closed without merging